# Generated by Django 4.0.4 on 2022-04-24 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank='True', null='True', upload_to='categorypics'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank='True', null='True', upload_to='subcategorypics'),
            preserve_default='True',
        ),
    ]
