# Generated by Django 4.0.4 on 2022-04-28 13:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_rename_discount_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
