# Generated by Django 4.0.4 on 2022-04-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0006_product_details_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('sessionid', models.CharField(max_length=200)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.product')),
            ],
        ),
    ]
